package fx.framework.themes;

public enum TypeFace {
	
	AGENCY_FB("Agency FB"),
	AHARONI("Aharoni"),
	ALGERIAN("Algerian"),
	ANDALUS("Andalus"),
	ANGSANA_NEW("Angsana New"),
	ANGSANAUPC("AngsanaUPC"),
	APARAJITA("Aparajita"),
	ARABIC_TYPESETTING("Arabic Typesetting"),
	ARIAL("Arial"),
	ARIAL_BLACK("Arial Black"),
	ARIAL_NARROW("Arial Narrow"),
	ARIAL_ROUNDED_MT_BOLD("Arial Rounded MT Bold"),
	BASKERVILLE_OLD_FACE("Baskerville Old Face"),
	BATANG("Batang"),
	BATANGCHE("BatangChe"),
	BAUHAUS_93("Bauhaus 93"),
	BELL_MT("Bell MT"),
	BERLIN_SANS_FB("Berlin Sans FB"),
	BERLIN_SANS_FB_DEMI("Berlin Sans FB Demi"),
	BERNARD_MT_CONDENSED("Bernard MT Condensed"),
	BLACKADDER_ITC("Blackadder ITC"),
	BODONI_MT("Bodoni MT"),
	BODONI_MT_BLACK("Bodoni MT Black"),
	BODONI_MT_CONDENSED("Bodoni MT Condensed"),
	BODONI_MT_POSTER_COMPRESSED("Bodoni MT Poster Compressed"),
	BOOK_ANTIQUA("Book Antiqua"),
	BOOKMAN_OLD_STYLE("Bookman Old Style"),
	BOOKSHELF_SYMBOL_7("Bookshelf Symbol 7"),
	BRADLEY_HAND_ITC("Bradley Hand ITC"),
	BRITANNIC_BOLD("Britannic Bold"),
	BROADWAY("Broadway"),
	BROWALLIA_NEW("Browallia New"),
	BROWALLIAUPC("BrowalliaUPC"),
	BRUSH_SCRIPT_MT("Brush Script MT"),
	CALIBRI("Calibri"),
	CALIBRI_LIGHT("Calibri Light"),
	CALIFORNIAN_FB("Californian FB"),
	CALISTO_MT("Calisto MT"),
	CAMBRIA("Cambria"),
	CAMBRIA_MATH("Cambria Math"),
	CANDARA("Candara"),
	CASTELLAR("Castellar"),
	CENTAUR("Centaur"),
	CENTURY("Century"),
	CENTURY_GOTHIC("Century Gothic"),
	CENTURY_SCHOOLBOOK("Century Schoolbook"),
	CHILLER("Chiller"),
	COLONNA_MT("Colonna MT"),
	COMIC_SANS_MS("Comic Sans MS"),
	CONSOLAS("Consolas"),
	CONSTANTIA("Constantia"),
	COOPER_BLACK("Cooper Black"),
	COPPERPLATE_GOTHIC_BOLD("Copperplate Gothic Bold"),
	COPPERPLATE_GOTHIC_LIGHT("Copperplate Gothic Light"),
	CORBEL("Corbel"),
	CORDIA_NEW("Cordia New"),
	CORDIAUPC("CordiaUPC"),
	COURIER_NEW("Courier New"),
	CURLZ_MT("Curlz MT"),
	DAUNPENH("DaunPenh"),
	DAVID("David"),
	DFKAI_SB("DFKai-SB"),
	DIALOG("Dialog"),
	DIALOGINPUT("DialogInput"),
	DILLENIAUPC("DilleniaUPC"),
	DOKCHAMPA("DokChampa"),
	DOTUM("Dotum"),
	DOTUMCHE("DotumChe"),
	DUBAI("Dubai"),
	DUBAI_LIGHT("Dubai Light"),
	DUBAI_MEDIUM("Dubai Medium"),
	EBRIMA("Ebrima"),
	EDWARDIAN_SCRIPT_ITC("Edwardian Script ITC"),
	ELEPHANT("Elephant"),
	ENGRAVERS_MT("Engravers MT"),
	ERAS_BOLD_ITC("Eras Bold ITC"),
	ERAS_DEMI_ITC("Eras Demi ITC"),
	ERAS_LIGHT_ITC("Eras Light ITC"),
	ERAS_MEDIUM_ITC("Eras Medium ITC"),
	ESTRANGELO_EDESSA("Estrangelo Edessa"),
	EUCROSIAUPC("EucrosiaUPC"),
	EUPHEMIA("Euphemia"),
	FANGSONG("FangSong"),
	FELIX_TITLING("Felix Titling"),
	FONT_AWESOME("FontAwesome", false),
	FOOTLIGHT_MT_LIGHT("Footlight MT Light"),
	FORTE("Forte"),
	FRANKLIN_GOTHIC_BOOK("Franklin Gothic Book"),
	FRANKLIN_GOTHIC_DEMI("Franklin Gothic Demi"),
	FRANKLIN_GOTHIC_DEMI_COND("Franklin Gothic Demi Cond"),
	FRANKLIN_GOTHIC_HEAVY("Franklin Gothic Heavy"),
	FRANKLIN_GOTHIC_MEDIUM("Franklin Gothic Medium"),
	FRANKLIN_GOTHIC_MEDIUM_COND("Franklin Gothic Medium Cond"),
	FRANKRUEHL("FrankRuehl"),
	FREESIAUPC("FreesiaUPC"),
	FREESTYLE_SCRIPT("Freestyle Script"),
	FRENCH_SCRIPT_MT("French Script MT"),
	GABRIOLA("Gabriola"),
	GADUGI("Gadugi"),
	GARAMOND("Garamond"),
	GAUTAMI("Gautami"),
	GEORGIA("Georgia"),
	GIGI("Gigi"),
	GILL_SANS_MT("Gill Sans MT"),
	GILL_SANS_MT_CONDENSED("Gill Sans MT Condensed"),
	GILL_SANS_MT_EXT_CONDENSED_BOLD("Gill Sans MT Ext Condensed Bold"),
	GILL_SANS_ULTRA_BOLD("Gill Sans Ultra Bold"),
	GILL_SANS_ULTRA_BOLD_CONDENSED("Gill Sans Ultra Bold Condensed"),
	GISHA("Gisha"),
	GLOUCESTER_MT_EXTRA_CONDENSED("Gloucester MT Extra Condensed"),
	GOUDY_OLD_STYLE("Goudy Old Style"),
	GOUDY_STOUT("Goudy Stout"),
	GULIM("Gulim"),
	GULIMCHE("GulimChe"),
	GUNGSUH("Gungsuh"),
	GUNGSUHCHE("GungsuhChe"),
	HAETTENSCHWEILER("Haettenschweiler"),
	HARLOW_SOLID_ITALIC("Harlow Solid Italic"),
	HARRINGTON("Harrington"),
	HELVETICANEUE("HelveticaNeue"),
	HIGH_TOWER_TEXT("High Tower Text"),
	IMPACT("Impact"),
	IMPRINT_MT_SHADOW("Imprint MT Shadow"),
	INFORMAL_ROMAN("Informal Roman"),
	IRISUPC("IrisUPC"),
	ISKOOLA_POTA("Iskoola Pota"),
	ITC_SERIF_GOTHIC("ITC Serif Gothic"),
	JASMINEUPC("JasmineUPC"),
	JOKERMAN("Jokerman"),
	JUICE_ITC("Juice ITC"),
	KAITI("KaiTi"),
	KALINGA("Kalinga"),
	KARTIKA("Kartika"),
	KHMER_UI("Khmer UI"),
	KODCHIANGUPC("KodchiangUPC"),
	KOKILA("Kokila"),
	KRISTEN_ITC("Kristen ITC"),
	KUNSTLER_SCRIPT("Kunstler Script"),
	LAO_UI("Lao UI"),
	LATHA("Latha"),
	LEELAWADEE("Leelawadee"),
	LEVENIM_MT("Levenim MT"),
	LILYUPC("LilyUPC"),
	LUCIDA_BRIGHT("Lucida Bright"),
	LUCIDA_CALLIGRAPHY("Lucida Calligraphy"),
	LUCIDA_CONSOLE("Lucida Console"),
	LUCIDA_FAX("Lucida Fax"),
	LUCIDA_HANDWRITING("Lucida Handwriting"),
	LUCIDA_SANS("Lucida Sans"),
	LUCIDA_SANS_TYPEWRITER("Lucida Sans Typewriter"),
	LUCIDA_SANS_UNICODE("Lucida Sans Unicode"),
	MAGNETO("Magneto"),
	MAIANDRA_GD("Maiandra GD"),
	MALGUN_GOTHIC("Malgun Gothic"),
	MANGAL("Mangal"),
	MARLETT("Marlett"),
	MATURA_MT_SCRIPT_CAPITALS("Matura MT Script Capitals"),
	MEIRYO("Meiryo"),
	MEIRYO_UI("Meiryo UI"),
	MICROSOFT_HIMALAYA("Microsoft Himalaya"),
	MICROSOFT_JHENGHEI("Microsoft JhengHei"),
	MICROSOFT_JHENGHEI_UI("Microsoft JhengHei UI"),
	MICROSOFT_NEW_TAI_LUE("Microsoft New Tai Lue"),
	MICROSOFT_PHAGSPA("Microsoft PhagsPa"),
	MICROSOFT_SANS_SERIF("Microsoft Sans Serif"),
	MICROSOFT_TAI_LE("Microsoft Tai Le"),
	MICROSOFT_UIGHUR("Microsoft Uighur"),
	MICROSOFT_YAHEI("Microsoft YaHei"),
	MICROSOFT_YAHEI_UI("Microsoft YaHei UI"),
	MICROSOFT_YI_BAITI("Microsoft Yi Baiti"),
	MINGLIU("MingLiU"),
	MINGLIU_EXTB("MingLiU-ExtB"),
	MINGLIU_HKSCS("MingLiU_HKSCS"),
	MINGLIU_HKSCS_EXTB("MingLiU_HKSCS-ExtB"),
	MIRIAM("Miriam"),
	MIRIAM_FIXED("Miriam Fixed"),
	MISTRAL("Mistral"),
	MODERN_NO_20("Modern No. 20"),
	MONGOLIAN_BAITI("Mongolian Baiti"),
	MONOSPACED("Monospaced"),
	MONOTYPE_CORSIVA("Monotype Corsiva"),
	MOOLBORAN("MoolBoran"),
	MS_GOTHIC("MS Gothic"),
	MS_MINCHO("MS Mincho"),
	MS_OUTLOOK("MS Outlook"),
	MS_PGOTHIC("MS PGothic"),
	MS_PMINCHO("MS PMincho"),
	MS_REFERENCE_SANS_SERIF("MS Reference Sans Serif"),
	MS_REFERENCE_SPECIALTY("MS Reference Specialty"),
	MS_UI_GOTHIC("MS UI Gothic"),
	MT_EXTRA("MT Extra"),
	MV_BOLI("MV Boli"),
	NARKISIM("Narkisim"),
	NIAGARA_ENGRAVED("Niagara Engraved"),
	NIAGARA_SOLID("Niagara Solid"),
	NIRMALA_UI("Nirmala UI"),
	NSIMSUN("NSimSun"),
	NYALA("Nyala"),
	OCR_A_EXTENDED("OCR A Extended"),
	OLD_ENGLISH_TEXT_MT("Old English Text MT"),
	ONYX("Onyx"),
	PALACE_SCRIPT_MT("Palace Script MT"),
	PALATINO_LINOTYPE("Palatino Linotype"),
	PAPYRUS("Papyrus"),
	PARCHMENT("Parchment"),
	PERPETUA("Perpetua"),
	PERPETUA_TITLING_MT("Perpetua Titling MT"),
	PLANTAGENET_CHEROKEE("Plantagenet Cherokee"),
	PLAYBILL("Playbill"),
	PMINGLIU("PMingLiU"),
	PMINGLIU_EXTB("PMingLiU-ExtB"),
	POOR_RICHARD("Poor Richard"),
	PRISTINA("Pristina"),
	RAAVI("Raavi"),
	RAGE_ITALIC("Rage Italic"),
	RAVIE("Ravie"),
	ROBOTO_BLACK("Roboto Black", false),
	ROBOTO_REGULAR("Roboto Regular", false),
	ROCKWELL("Rockwell"),
	ROCKWELL_CONDENSED("Rockwell Condensed"),
	ROCKWELL_EXTRA_BOLD("Rockwell Extra Bold"),
	ROD("Rod"),
	SAKKAL_MAJALLA("Sakkal Majalla"),
	SANSSERIF("SansSerif"),
	SCRIPT_MT_BOLD("Script MT Bold"),
	SEGOE_PRINT("Segoe Print"),
	SEGOE_SCRIPT("Segoe Script"),
	SEGOE_UI("Segoe UI"),
	SEGOE_UI_LIGHT("Segoe UI Light"),
	SEGOE_UI_SEMIBOLD("Segoe UI Semibold"),
	SEGOE_UI_SEMILIGHT("Segoe UI Semilight"),
	SEGOE_UI_SYMBOL("Segoe UI Symbol"),
	SERIF("Serif"),
	SHONAR_BANGLA("Shonar Bangla"),
	SHOWCARD_GOTHIC("Showcard Gothic"),
	SHRUTI("Shruti"),
	SIMHEI("SimHei"),
	SIMPLIFIED_ARABIC("Simplified Arabic"),
	SIMPLIFIED_ARABIC_FIXED("Simplified Arabic Fixed"),
	SIMSUN("SimSun"),
	SIMSUN_EXTB("SimSun-ExtB"),
	SNAP_ITC("Snap ITC"),
	STENCIL("Stencil"),
	SWIS721_BT("Swis721 BT"),
	SYLFAEN("Sylfaen"),
	SYMBOL("Symbol"),
	TAHOMA("Tahoma"),
	TEMPUS_SANS_ITC("Tempus Sans ITC"),
	TIMES_NEW_ROMAN("Times New Roman"),
	TRADITIONAL_ARABIC("Traditional Arabic"),
	TREBUCHET_MS("Trebuchet MS"),
	TUNGA("Tunga"),
	TW_CEN_MT("Tw Cen MT"),
	TW_CEN_MT_CONDENSED("Tw Cen MT Condensed"),
	TW_CEN_MT_CONDENSED_EXTRA_BOLD("Tw Cen MT Condensed Extra Bold"),
	UTSAAH("Utsaah"),
	VANI("Vani"),
	VERDANA("Verdana"),
	VIJAYA("Vijaya"),
	VINER_HAND_ITC("Viner Hand ITC"),
	VIVALDI("Vivaldi"),
	VLADIMIR_SCRIPT("Vladimir Script"),
	VRINDA("Vrinda"),
	WEBDINGS("Webdings"),
	WIDE_LATIN("Wide Latin"),
	WINGDINGS("Wingdings"),
	WINGDINGS_2("Wingdings 2"),
	WINGDINGS_3("Wingdings 3");
	
	private static final String FONT_LOCATION = "/fonts/";
	
	public String font;
	boolean system = true;
	
	TypeFace(String font){
		this.font = font;
	}
	
	TypeFace(String font, boolean system){
		this(font);
		this.system = system;
	}
	
	public boolean needsLoading(){
		return !system;
	}
	
	public String filename(){
		return FONT_LOCATION + font.replace(" ", "-") + ".ttf";
	}

}
